// <auto-generated />
namespace Time_Table_Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TablesGenerated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablesGenerated));
        
        string IMigrationMetadata.Id
        {
            get { return "202103071149330_TablesGenerated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
